# --- Builder ---
FROM golang:1.25.3-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o server ./cmd/main.go


# --- Final image ---
FROM gcr.io/distroless/static-debian11

WORKDIR /app
COPY --from=builder /app/server .

EXPOSE 8080
CMD ["./server"]
